let data = {
    "config": {
        "image_default": "https://s3.amazonaws.com/gt7sp-prod/decal/20/65/90/4684386837524906520_1.png",
        "currency_default": "руб",
        "description": "Для бронирования обращаться к <a href=\"tg://resolve?domain=musat_t\">Мусатику</a>",
        "show_archived": 1,
    },
    "items": [
        {
            "name": "Бэнвэ",
            "price": "1500000",
            "currency": "(деревянных)",
            "image": "https://a.d-cd.net/eb560aas-960.jpg",
            "tags": ["машина"],
            "url": "tg://resolve?domain=musat_t\/",
            "multi": 1,
        },
        {
            "name": "Шуруповёрт Makita DF333DWME",
            "price": 10500,
            "currency": "(деревянных)",
            "tags": ["техника"],
            "url": "https://makita.vseinstrumenti.ru/instrument/shurupoverty/akkumulyatornye-dreli/bezudarnye/shurupovert-df333dwme/#tab3",
            "image": "https://cdn.vseinstrumenti.ru/images/goods/instrument/shurupoverty/964585/560x504/52421826.jpg",
        },
        {
            "name": "Набор бит 37 шт. Makita B-28606",
            "price": 1700,
            "currency": "(деревянных)",
            "tags": ["техника"],
            "url": "https://makita.vseinstrumenti.ru/rashodnie_materialy/instrument/dlya_gaykovertov_vintovertov_i_shurupovertov/nasadki/nabory_bit/makita_nabor_bit_37_sht_b-28606-10/",
            "image": "https://cdn.vseinstrumenti.ru/images/goods/rashodnie-materialy/instrument/765125/560x504/51447978.jpg",
        },
        {
            "name": "Настольная игра 'Покорение марса: Колонии'",
            "price": 2150,
            "tags": ["настолки"],
            "url": "https://hobbygames.ru/pokorenie-marsa-kolonii",
            "image": "https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Lavka_Games/Pokorenie_Marsa/Colonies/pokoreniemarsa-1024x1024-wm.jpg",
        },
        {
            "name": "Наушники Sony WH-1000XM4",
            "price": 30000,
            "tags": ["техника"],
            "url": "https://store.sony.ru/product/naushniki-sony-wh-1000xm4-317432/",
            "image": "https://store.sony.ru/common/img/catalogue/317432/5d02da5df552836db894cead8a68f5f3-big.png",
        },
        {
            "name": "Футболка Dead Cells: The Island",
            "price": 24,
            "currency": "$",
            "tags": ["футболки"],
            "url": "https://www.fangamer.com/collections/dead-cells/products/dead-cells-logo-shirt",
            "image": "https://cdn.shopify.com/s/files/1/0014/1962/products/product_DeadCells_TheIsland_shirt_photo1_1024x1024.png?v=1566606405",
            "description": "Размер M",
        },
        {
            "name": "Виски Oban malt 14 years old",
            "price": 6500,
            "tags": ["алкоголь"],
            "url": "https://winestyle.ru/products/Oban-malt-14-years-old-with-box.html",
            "image": "https://skygarden.azureedge.net/media/images/products/2019/02/product_image_66b99a62-658d-4018-a8ea-998a174b0231.jpg",
            "archived": 1,
        },
    ]
}
