let data = {
    "config": {
        "image_default": "https://s3.amazonaws.com/gt7sp-prod/decal/20/65/90/4684386837524906520_1.png",
        "currency_default": "руб",
        "description": "Для бронирования обращаться к <a href=\"tg://resolve?domain=musat_t\">Мусатику</a>",
        "show_archived": 1,
    },
    "items": [
        {
            "name": "Бэнвэ",
            "price": "1500000",
            "currency": "(деревянных)",
            "image": "https://a.d-cd.net/eb560aas-960.jpg",
            "tags": ["машина"],
            "url": "tg://resolve?domain=musat_t\/",
            "multi": 1,
        },
        {
            "name": "Apple AirPods Pro",
            "price": 25000,
            "tags": ["техника"],
            "url": "https://www.mvideo.ru/products/naushniki-apple-airpods-pro-with-magsafe-case-mlwk3ru-a-50165904",
            "image": "https://img.mvideo.ru/Big/50165904bb.jpg",
        },
        {
            "name": "Apple Watch Series 7",
            "price": 40000,
            "tags": ["техника"],
            "url": "https://www.mvideo.ru/products/smart-chasy-apple-watch-series-7-gps-45mm-midnightal-midnight-sport-30059215",
            "image": "https://img.mvideo.ru/Big/30059215bb.jpg",
        },
        {
            "name": "Настольная игра 'Покорение марса: Колонии'",
            "price": 2150,
            "tags": ["настолки"],
            "url": "https://hobbygames.ru/pokorenie-marsa-kolonii",
            "image": "https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Lavka_Games/Pokorenie_Marsa/Colonies/pokoreniemarsa-1024x1024-wm.jpg",
        },
        {
            "name": "Наушники Sony WH-1000XM4",
            "price": 30000,
            "tags": ["техника"],
            "url": "https://store.sony.ru/product/naushniki-sony-wh-1000xm4-317432/",
            "image": "https://store.sony.ru/common/img/catalogue/317432/5d02da5df552836db894cead8a68f5f3-big.png",
        },
        {
            "name": "Дюна. Иллюстрированная история создания классики научной фантастики",
            "price": 4500,
            "tags": ["артбуки"],
            "url": "https://eksmo.ru/book/dyuna-illyustrirovannaya-istoriya-sozdaniya-klassiki-nauchnoy-fantastiki-ITD1177428/",
            "image": "https://cdn.eksmo.ru/v2/ITD000000001177428/COVER/cover1__w820.jpg",
        },
        {
            "name": "Настольная игра 'Немезида'",
            "price": 12000,
            "tags": ["настолки"],
            "url": "https://hobbygames.ru/nemezida",
            "image": "https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/HobbyWorld/Nemesis/HG/Nemesis_01-1024x1024-wm.jpg",
        },
        {
            "name": "Hacker gift",
            "price": 20,
            "currency": "$",
            "tags": ["geek"],
            "url": "https://hacker.gifts/",
            "image": "https://cdn.shopify.com/s/files/1/0013/8539/8385/products/card_1_1024x1024.png",
        },
        {
            "name": "Комикс-игра 'Похищение'",
            "price": 800,
            "tags": ["комиксы"],
            "url": "https://hobbygames.ru/komiks-igra-pohishhenie",
            "image": "https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/HobbyWorld/Komiks_igra_pohishenije/Pohichenie-1024x1024-wm.jpg"
        },
        {
            "name": "Комикс Preacher (Hardcover) Book Four и последующие",
            "price": 27,
            "currency": "$",
            "tags": ["комиксы"],
            "url": "https://www.amazon.com/Preacher-Book-Four-Garth-Ennis/dp/1401230938",
            "image": "https://cdn1.ozone.ru/multimedia/1010438854.jpg"
        },
        {
            "name": "Футболка Hollow Knight: Troupe Master",
            "price": 24,
            "currency": "$",
            "tags": ["футболки"],
            "url": "https://www.fangamer.com/collections/hollow-knight/products/grimm-hollow-knight-shirt",
            "image": "https://cdn.shopify.com/s/files/1/0014/1962/products/product_HK_troupe_master_shirt_photo1_1024x1024.png?v=1563036118",
            "description": "Размер M",
        },
        {
            "name": "Футболка God of War: Greatest Challenge",
            "price": 24,
            "currency": "$",
            "tags": ["футболки"],
            "url": "https://www.fangamer.com/products/god-of-war-lake-shirt",
            "image": "https://cdn.shopify.com/s/files/1/0014/1962/products/product_GoW_greatestchallenge_shirt_photo1_1024x1024.png?v=1569533503",
            "description": "Размер M",
        },
        {
            "name": "Футболка Celeste: Sides",
            "price": 24,
            "currency": "$",
            "tags": ["футболки"],
            "url": "https://www.fangamer.com/collections/celeste/products/celeste-cassette-shirt",
            "image": "https://cdn.shopify.com/s/files/1/0014/1962/products/product_celeste_sides_shirt_photo1_1024x1024.png?v=1580160195",
            "description": "Размер M",
        },
        {
            "name": "Футболка Myst: Mystic Arcana",
            "price": 24,
            "currency": "$",
            "tags": ["футболки"],
            "url": "https://www.fangamer.com/collections/myst/products/myst-arcana-shirt",
            "image": "https://cdn.shopify.com/s/files/1/0014/1962/products/product_myst_mystic-arcana_shirt_main_1024x1024.png?v=1594744035",
            "description": "Размер M",
        },
        {
            "name": "Футболка Dead Cells: The Island",
            "price": 24,
            "currency": "$",
            "tags": ["футболки"],
            "url": "https://www.fangamer.com/collections/dead-cells/products/dead-cells-logo-shirt",
            "image": "https://cdn.shopify.com/s/files/1/0014/1962/products/product_DeadCells_TheIsland_shirt_photo1_1024x1024.png?v=1566606405",
            "description": "Размер M",
        },
        {
            "name": "Lego Batwing (76161)",
            "price": 19000,
            "tags": ["lego"],
            "url": "https://mir-kubikov.ru/lego/76161/",
            "image": "https://static.mir-kubikov.ru/upload/resize_cache/iblock/551/746_580_140cd750bba9870f18aada2478b24840a/551158b8c1a2e0c0787a9f5c25dd9936.jpg"
        },
        {
            "name": "Фигурка-утка Tubbz Зефирный человек",
            "price": 1800,
            "tags": ["утки"],
            "url": "https://www.respublica.ru/detyam/igrushki-i-igry/figurki/588170-figurka-utka-tubbz-ohotniki-za-privideniyami-zefirnyy-chelovek",
            "image": "https://www.respublica.ru/uploads/01/00/00/ew/9f/large_86fc5e3aca97d574.jpg"
        },
        {
            "name": "Фигурка-утка Tubbz Гимли",
            "price": 1800,
            "tags": ["утки"],
            "url": "https://www.respublica.ru/detyam/igrushki-i-igry/figurki/588151-figurka-utka-tubbz-vlastelin-kolets-gimli",
            "image": "https://www.respublica.ru/uploads/01/00/00/ev/zj/large_7d4f1650425c1d35.jpg"
        },
        {
            "name": "Hollow Knight Pin",
            "price": 10,
            "currency": "$",
            "tags": ["pins"],
            "url": "https://www.fangamer.com/products/hollow-knight-pin",
            "image": "https://cdn.shopify.com/s/files/1/0014/1962/products/product_HK_wanderer_lapel_main_1024x1024.jpg?v=1541195039"
        },
        {
            "name": "Saw Cleaver Pin",
            "price": 12,
            "currency": "$",
            "tags": ["pins"],
            "url": "https://www.fangamer.com/collections/bloodborne/products/bloodborne-saw-cleaver-pin",
            "image": "https://cdn.shopify.com/s/files/1/0014/1962/products/product_bloodborne_plain-doll-hand_pin_main_e65bc9c5-8daf-4b52-9072-ee0204c7a389_1024x1024.png?v=1592247200"
        },
        {
            "name": "Стикерпак Fallout",
            "price": 250,
            "image": "https://www.parazitakusok.ru/images/item/3705/bez_imeni-1.jpg",
            "tags": ["стикеры"],
            "url": "https://www.parazitakusok.ru/item/3705/",
            "date": "2020-07-08"
        },
        {
            "name": "Виски Oban malt 14 years old",
            "price": 6500,
            "tags": ["алкоголь"],
            "url": "https://winestyle.ru/products/Oban-malt-14-years-old-with-box.html",
            "image": "https://skygarden.azureedge.net/media/images/products/2019/02/product_image_66b99a62-658d-4018-a8ea-998a174b0231.jpg",
            "archived": 1,
        },
        {
            "name": "New Super Mario Bros U Deluxe",
            "price": 3800,
            "tags": ["игры", "switch"],
            "url": "https://www.mvideo.ru/products/igra-nintendo-switch-new-super-mario-bros-u-deluxe-40070863",
            "image": "https://img.mvideo.ru/Pdb/40070863b.jpg",
            "archived": 1,
        },
        {
            "name": 'Настольная игра «Покорение Марса»',
            "price": 4000,
            "tags": ["настолки"],
            "url": "https://hobbygames.ru/pokorenie-marsa",
            "image": "https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Lavka_Games/Pokorenie_Marsa/Proekt_Venera/Pokorenie_Marsa-1024x1024-wm.jpg",
            "archived": 1,
        },
        {
            "name": "Настольная игра 'Покорение марса: Кризис'",
            "price": 2300,
            "tags": ["настолки"],
            "url": "https://hobbygames.ru/pokorenie-marsa-krizis",
            "image": "https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Lavka_Games/Pokorenie_Marsa/Krizis/Pokorenie_Marsa_Krizis-1024x1024-wm.jpg",
            "archived": 1,
        },
        {
            "name": "Настольная игра 'Покорение марса: Эллада и Элизий'",
            "price": 1250,
            "tags": ["настолки"],
            "url": "https://hobbygames.ru/pokorenie-marsa-jellada-i-jelizij",
            "image": "https://hobbygames.cdnvideo.ru/image/cache/hobbygames_beta/data/Lavka_Games/Pokorenie_Marsa/Proekt_Venera/Pokorenie_Marsa_Ellada_i_Eliziy-1024x1024-wm.jpg",
            "archived": 1,
        },
        {
            "name": "The Legend of Zelda: Link's Awakening",
            "price": 3800,
            "tags": ["игры", "switch"],
            "url": "https://www.mvideo.ru/products/igra-nintendo-switch-the-legend-of-zelda-link-s-awakening-40071643",
            "image": "https://img.mvideo.ru/Pdb/40071643b.jpg",
            "archived": 1
        },
        {
            "name": "Lego R2-D2 (75308)",
            "price": 19000,
            "tags": ["lego"],
            "url": "https://mir-kubikov.ru/lego/75308/",
            "image": "https://static.mir-kubikov.ru/upload/resize_cache/iblock/e62/746_580_140cd750bba9870f18aada2478b24840a/e6257684e6a453030f0a2516be8e56c6.jpg",
            "archived": 1
        },
        {
            "name": "DOOM. Как в битвах с демонами закалялся новый жанр",
            "price": 655,
            "tags": ["книги"],
            "url": "https://book24.ru/product/doom-kak-v-bitvakh-s-demonami-zakalyalsya-novyy-zhanr-5907841/",
            "image": "https://cdn.book24.ru/v2/ITD000000001110467/COVER/cover3d1__w337.webp",
            "archived": 1
        },
        {
            "name": "Дарт Вейдер. Тёмный повелитель ситхов (Чарльз Соул)",
            "price": 2050,
            "tags": ["комиксы"],
            "url": "https://www.chookandgeek.ru/product/dart-veyder-tyomnyy-povelitel-sithov",
            "image": "https://static-sl.insales.ru/images/products/1/5169/382735409/large_1.jpg",
            "archived": 1
        },
        {
            "name": "Звёздные Войны. Дарт Вейдер. Полное издание (Кирон Гиллен)",
            "price": 1750,
            "tags": ["комиксы"],
            "url": "https://www.respublica.ru/knigi/hudozhestvennaya-literatura/komiksy-i-manga/515545-gillen-k-zvyozdnye-voyny-dart-veyder-polnoe-izdanie-zvezdnye-voyny-dart-veyder-t-o",
            "image": "https://www.respublica.ru/uploads/01/00/00/c3/4l/large_851bd1a5a53f2750.jpg",
            "archived": 1
        },
           {
            "name": "Техносвященники. Том второй",
            "price": 1240,
            "tags": ["комиксы"],
            "url": "https://www.labirint.ru/books/744320/",
            "image": "https://img4.labirint.ru/rc/c1b5ccf2fc15a72a72349dcd767a0980/220x340/books75/744320/cover.jpg?1585200359",
            "archived": 1
        },
        {
            "name": "Apple iPad 2019 32GB Wi-Fi Space Gray",
            "price": 26000,
            "tags": ["техника"],
            "url": "https://biggeek.ru/products/apple-ipad-2019-32gb-wi-fi-space-gray",
            "image": "https://cdn2.biggeek.ru/1/435/711c/9900-385ipad-wifi-select-space-201909_GEO_RU.png",
            "archived": 1,
        },
        {
            "name": "Lego Экстремальный внедорожник",
            "price": 12500,
            "tags": ["lego"],
            "url": "https://mir-kubikov.ru/lego/42099/",
            "image": "https://mir-kubikov.ru/upload/resize_cache/iblock/6b2/670_520_140cd750bba9870f18aada2478b24840a/6b23f2e4088abd8b6f802fa4e1792f92.jpg",
            "archived": 1,
        },
        {
            "name": "Lego Batmobile",
            "price": 20000,
            "image": "https://mir-kubikov.ru/upload/resize_cache/iblock/b2a/746_580_140cd750bba9870f18aada2478b24840a/b2af09393c7e0bc105372029af274a56.jpg",
            "tags": ["lego"],
            "url": "https://mir-kubikov.ru/lego/76139/",
            "archived": 1,
        },
        {
            "name": "Рюкзак Nomatic Travel Pack",
            "price": 21600,
            "image": "https://cdn.shopify.com/s/files/1/0745/1299/products/travel-pack_1024x1024.jpg?v=1588217895",
            "tags": ["полезное"],
            "url": "https://www.bagandwallet.ru/collection/nomatic/product/nomatic_travel_pack_kupit",
            "archived": 1,
        },
                {
            "name": "Техносвященники. Том первый",
            "price": 1400,
            "tags": ["комиксы"],
            "url": "https://www.labirint.ru/books/731757/",
            "image": "https://img3.labirint.ru/rc/9ee30ed65a26f742e7dac59db4abeba3/220x340/books74/731757/cover.jpg?1577273210",
            "archived": 1,
        },
    ]
}
